# -*- coding: utf-8 -*-
"""QR code .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_9BROJ72u-8uLUoHdebvuGFSZir9RJJ
"""

!apt install libzbar0

!pip install pyzbar

from google.colab import files
from IPython import display
import pyzbar.pyzbar as pyzbar

uploaded = files.upload()

image = display.Image('my _qrcode.png')
image

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('/content/my _qrcode.png')

decodedObjects = pyzbar.decode(image)
for obj in decodedObjects :
  print(obj)
  print('=================')
  print('Type :', obj.type)
  print('Data : ', obj.data, '\n')



image = cv2_imshow(image)
cv2.waitKey(0)